### ISSUE TITLE
Update to eslint 5

### ISSUE THREAD

**Issue by alexashley** [manovotny/eslint-config-get-off-my-lawn#102]
With the exception of the issue in #101, everything appears to work correctly.

[Migration guide](https://eslint.org/docs/user-guide/migrating-to-5.0.0)

I'd be happy to make an attempt at this if desired.

**Comment by manovotny** [comment]
Usually when I updated eslint, I also comb the release notes for new rules I want to enable.

I'll see if I can get it done this week.

**Comment by manovotny** [comment]
Fixed in #105.
