### ISSUE TITLE
Update babel-eslint to fix false positive error when using for of syntax

### ISSUE THREAD

**Issue by bgoerdt** [manovotny/eslint-config-get-off-my-lawn#127]
We are getting a no-unused-vars error when using `for...of` syntax. It is due to a bug in babel-eslint, and was fixed in version 10.0.3.

Here is the relevant comment on the babel-eslint issue: https://github.com/babel/babel-eslint/issues/791#issuecomment-524664585

**Comment by manovotny** [comment]
This should be fixed in #133. 🔜
