### ISSUE TITLE
change from babel-eslint to @babel/eslint-parser

### ISSUE THREAD

**Issue by AndreasChristianson** [manovotny/eslint-config-get-off-my-lawn#146]
## problem

I found that I was affected by https://github.com/babel/babel/issues/10904

```
yarn run v1.22.10
$ eslint .

Oops! Something went wrong! :(

ESLint: 7.18.0

TypeError: Cannot read property 'value' of null
```
I can provide more context or a mcve if needed.

## workaround

I worked around this problem by overriding the parser in the .eslintrc.js that consumes this config:
```
module.exports = {
    extends: [
        'get-off-my-lawn'
    ],
    parser: '@babel/eslint-parser'
}
```

## potential solution

Could we switch to @babel/eslint-parser as our parser [here](https://github.com/manovotny/eslint-config-get-off-my-lawn/blob/ba03c52a326c3da8b1af99243497667056beffb7/index.js#L30)?

I'm willing to submit a pr for this solution.

**Comment by manovotny** [comment]
This will fixed in #133.
