### ISSUE TITLE
Add a rule to address `reduce` performance issues

### ISSUE THREAD

**Issue by manovotny** [manovotny/eslint-config-get-off-my-lawn#156]
One of the teams I work with recently discovered a performance improvement they made by swapping a [`reduce`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce) call with a standard `forEach` for a ~2x performance improvement. The specific use case that was uncovered was in regard to `reduce...spread`, which is [eloquently articulated in an article](https://www.richsnapp.com/article/2019/06-09-reduce-spread-anti-pattern) by @snapwich. 

This led me to run some tests on [JSBench.me](https://jsbench.me).

### Looping

Here's an [example](https://jsbench.me/0sknywh784) and screenshot of the results below.

![screencapture-jsbench-me-0sknywh784-2021-04-27-20_38_34](https://user-images.githubusercontent.com/446260/116333428-09222680-a799-11eb-8abe-a862dcfc85ac.png)

### Summing

Here's an [example](https://jsbench.me/wsko0sex6z) and screenshot of the results below. This should be the premier use case for `reduce`. 

![screencapture-jsbench-me-wsko0sex6z-2021-04-27-20_40_16](https://user-images.githubusercontent.com/446260/116333448-0fb09e00-a799-11eb-8c29-fa289970293b.png)

### How come my test results are different?

Results will differ depending on browser. For example, Safari seems to have optimized `forEach` better than Chrome. The screenshots above were from the tests running in Chrome.

### Aren't all HOFs slower?

Yes, all higher order functions (aka. HOFs) are slower than direct array / object manipulation, by their nature (ie. `reduce`, `map`, `filter`, etc.). The entire reason for using the HOFs is for expressivity. You can declare what you want to happen rather than how you want it to happen. Their expressiveness does dramatically simplify implementation is most cases, reducing cognitive overload and reducing the chance of introducing bugs into manual looping logic. 

More reading: 

* [Higher-Order Functions](https://eloquentjavascript.net/05_higher_order.html)
* [Understanding Higher-Order Functions in JavaScript](https://blog.bitsrc.io/understanding-higher-order-functions-in-javascript-75461803bad)

### We shouldn't have to worry about the code we write, shouldn't processors / transpilers solve this for us?

Yes and no. 

Yes, transpilers / compilers _can_ transform these functions into their traditional looping logic, but it also depends on the configuration. 

1. They either need to be explicitly configured to do so.
1. If using something like [browserslist](https://github.com/browserslist/browserslist) and only targeting modern browsers, which all support these new functions, it will not be transpiled.
1. Most pure node code (ie. APIs, CLIs, etc.) will not have any transpilation / compilation process.

### Do I really need to care about the performance of this?

Maybe? 🤷‍♂️ 

Context is key here. 

Are you going to notice poor performance if you're iterating over a dozen items or so? There could be a 1ms - 2ms overhead there, but in reality, you likely won't notice a thing. 

Now if you're talking about an API, CLI, etc. that is processing hundreds, thousands, millions, and beyond, it's all going to add up and you're going to see a noticeable performance hit. 

## Possibilities 

As you can see, `reduce` (and its other HOF friends) can be a bit of a in compared to alternatives. 🐶 

With that said, I see the following paths forward here.

### Option 1: Do nothing

At least lint rule wise and raise awareness of performance implications during PR reviews.

This option has the least likelihood of making any difference whatsoever.

### Option 2: Add an ESLint rule just for `reduce…spread`

Takes care of the worst offender, but doesn't necessarily address the fact that this HOF it's a poor performer in all aspects.

### Option 3: Add an ESLint rule for anything with a `reduce` who’s initialValue is `[]` or `{}`

Goes one step further than Option 2 and essentially limits `reduce` usage to summing of numbers.

### Option 4: Add an ESLint rule to disallow `no-param-reassign`, but allow it for use within `reduce`

I don't have interest in maintaining my own `no-param-reassign` rule to accommodate this, so the only path forward I'd consider here is adding an option like `allowInReduce` to the [official ESLint `no-param-reassign` rule](https://eslint.org/docs/rules/no-param-reassign) and submitting a PR.

### Option 5: Add an ESLint rule to disallow `reduce` altogether

There is already a rule for this, [unicorn/no-array-reduce](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-array-reduce.md) and it's description is not wrong...

> `Array#reduce()` and `Array#reduceRight()` usually [result in hard-to-read code](https://twitter.com/jaffathecake/status/1213077702300852224). In almost every case, it can be replaced by `.map`, `.filter`, or a `for-of` loop. It's only somewhat useful in the rare case of summing up numbers.
> 
> Use `eslint-disable` comment if you really need to use it.

**Comment by busches** [comment]
I know this is a contrived example, but using spread in `reduce` seems like an anti-pattern all around. In this example, you're making 1000 new objects to throw them away immediately. Modifying it to be similar to the `forEach` example, doesn't result in mutation (outside of the reduce itself, which is fine IMO) and is more performant than the `forEach` example and avoids the `let merged` which was the goal. While not pure FP (I guess?), it gets the job done.

```js
const merged = array.reduce((accumulator, {id, value}) => {
	accumulator[id] = value;
	return accumulator;
}, {});
```

So I'm for option 2, option 5 is likely also mostly true. The times I've had to use `reduce`, that come to mind, are when summing.

**Comment by manovotny** [comment]
Choosing to address this with [unicorn/no-array-reduce](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-array-reduce.md) rule, which was enhanced with the [`allowSimpleOperations` option](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-array-reduce.md#allowsimpleoperations), which seems like decent compromise. This will fixed with the [v7 release](https://github.com/manovotny/eslint-config-get-off-my-lawn/pull/173).
