### ISSUE TITLE
Update eslint-plugin-jest to version 24.3.3

### ISSUE THREAD

**Issue by cortl** [manovotny/eslint-config-get-off-my-lawn#172]
There is a bug for multiple hooks lint rule when using `describe.each` that has been fixed in version 24.3.3 of eslint-plugin-jest

Related issue jest-community/eslint-plugin-jest#642

**Comment by manovotny** [comment]
Thanks for letting me know. I already have the v7 branch (#173) using version `24.4.2` of `eslint-plugin-jest`.
