### ISSUE TITLE
7.0.0-beta.7 breaks on node < 14.18.0

### ISSUE THREAD

**Issue by bskiff** [manovotny/eslint-config-get-off-my-lawn#181]
Error output:

```
Oops! Something went wrong! :(

ESLint: 8.7.0

Error: Cannot read config file: /Users/ben.skiff/Developer/shopify-proxy-api/node_modules/eslint-config-get-off-my-lawn/index.js
Error: Cannot find module 'node:path'
Require stack:
- /Users/ben.skiff/Developer/shopify-proxy-api/node_modules/eslint-config-get-off-my-lawn/src/utils/files.js
- /Users/ben.skiff/Developer/shopify-proxy-api/node_modules/eslint-config-get-off-my-lawn/src/utils/dependencies.js
- /Users/ben.skiff/Developer/shopify-proxy-api/node_modules/eslint-config-get-off-my-lawn/src/babel.js
- /Users/ben.skiff/Developer/shopify-proxy-api/node_modules/eslint-config-get-off-my-lawn/index.js
- /Users/ben.skiff/Developer/shopify-proxy-api/node_modules/@eslint/eslintrc/dist/eslintrc.cjs
- /Users/ben.skiff/Developer/shopify-proxy-api/node_modules/eslint/lib/cli-engine/cli-engine.js
- /Users/ben.skiff/Developer/shopify-proxy-api/node_modules/eslint/lib/eslint/eslint.js
- /Users/ben.skiff/Developer/shopify-proxy-api/node_modules/eslint/lib/eslint/index.js
- /Users/ben.skiff/Developer/shopify-proxy-api/node_modules/eslint/lib/cli.js
- /Users/ben.skiff/Developer/shopify-proxy-api/node_modules/eslint/bin/eslint.js
Referenced from: /Users/ben.skiff/Developer/example-project/.eslintrc.json
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (/Users/ben.skiff/Developer/example-project/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/ben.skiff/Developer/example-project/node_modules/eslint-config-get-off-my-lawn/src/utils/files.js:1:78)
    at Module._compile (/Users/ben.skiff/Developer/example-project/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
```

I observed that:
 * working: `16.13.2` `14.18.2`
 * not working: `14.16.1`, `14.15.4`

The current stable version of VSCode(`1.63.2`) uses node `14.16.0`. This causes the ESLint VSCode extension to fail to load.

As part of troubleshooting, I tried changing the imports of `require('node:path')` to `require('path')` and `require('node:process')` to `require('process')` within my node_modules, and that resolved the issue.

**Comment by bskiff** [comment]
It looks like support for the `node:` imports was added in `14.18.0`: https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V14.md#14.18.0

**Comment by manovotny** [comment]
@bskiff this is an excellent catch!!! [GOML is even configured to account for this](https://github.com/manovotny/eslint-config-get-off-my-lawn/pull/173/files#diff-583da91e02279bb45f1120e13343cce6c330beb9b0469fca50510675e742fc8dR117-R128), but I didn't even think about using it myself and then what that would do to _consumers_ of GOML. 🤦‍♂️ 

While [Node 12 is in maintenance mode](https://endoflife.date/nodejs), it (specifically version `12.20.0`and above) is playing a critical part in [pure ESM](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c) adoption. 

I'm going to see if I can enhance the aforementioned check on enforcing the rule... I'll report back. Thanks again for the report! 🙏

**Comment by manovotny** [comment]
Ok, I think I landed in a good place here with this commit (https://github.com/manovotny/eslint-config-get-off-my-lawn/pull/173/commits/17f5575ed9a586bd8b401be7d61eeae20955fc79).

* Changed all the `prefer-global` rules to `never`, which will make transitioning packages to ESM easier.
* Conditionally enables rules for checking for node protocol (ie. `node:`) based on the current version of node being used and what the package has listed in its `engines`. 
* Removed the node protocol (ie. `node:`) from GMOL's internal use.

This will be fixed in the next beta or final release.
